import { test } from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { setTimeout as delay } from "node:timers/promises";
import { apply, __setTestHooks } from "../../index.js";
import { saveProject, runDirOf, writeArtifact } from "../../lib/core/store.js";
import { saveRun, loadRun } from "../../lib/core/pipeline.js";
import p6 from "../../lib/stages/p6-coder.js";

test("Claude 活动联调：P6 流式采集在执行中可读，读取不写任务，重跑隔离及停止固定时间", { timeout: 15_000 }, async t => {
    const root = mkdtempSync(join(tmpdir(), "i2p-activity-http-"));
    __setTestHooks({ dataRoot: root });
    let server, execution, complete;
    t.after(async () => {
        complete?.();
        await execution;
        if (server?.listening) await new Promise(resolve => server.close(resolve));
        __setTestHooks(null);
        rmSync(root, { recursive: true, force: true });
    });
    const routes = [];
    apply({ effect(fn) { fn(); }, logger: { info() {} }, webServer: { register(spec) { routes.push(spec); } } });
    saveProject(root, { slug: "activity", name: "Activity", repos: ["https://example.test/activity.git"], triggers: [], reviewMode: "every", p6Mode: "claude" });
    const id = "20260914-120000-activity", runDir = runDirOf(root, "activity", id), start = new Date().toISOString();
    const run = { id, p6Mode: "claude", status: "running", current: "P6", stages: { P6: { status: "running", startedAt: start } } };
    saveRun(runDir, run);
    writeArtifact(runDir, "05-task-graph.json", JSON.stringify({ nodes: [{ id: "T1", title: "修复测试案例", output: "patch", deps: [] }] }));
    server = createServer((req, res) => routes[0].handler(req, res));
    await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
    const base = `http://127.0.0.1:${server.address().port}/issue2pr/api/projects/activity/runs/${id}`;
    const get = async () => {
        const response = await fetch(base);
        assert.equal(response.status, 200);
        assert.equal(response.headers.get("cache-control"), "no-store");
        return response.json();
    };
    let send;
    const child = { pid: 0, exitCode: null, signalCode: null };
    const held = new Promise(resolve => { complete = resolve; });
    let ready;
    const spawned = new Promise(resolve => { ready = resolve; });
    execution = p6({ runDir, repoDir: root, run, llm: {}, p6Mode: "claude", spawnExternal: async opts => {
        opts.onChild(child);
        let stdout = "";
        send = frame => { const line = JSON.stringify(frame) + "\n"; stdout += line; opts.onStdoutChunk(line); };
        send({ type: "assistant", message: { content: [{ type: "tool_use", id: "npm", name: "Bash", input: { command: "npm install", description: "安装依赖", run_in_background: true } }] } });
        send({ type: "system", subtype: "task_started", task_id: "install", tool_use_id: "npm", description: "安装依赖", is_backgrounded: true });
        send({ type: "user", message: { content: [{ type: "tool_result", tool_use_id: "npm", content: "Command running in background" }] }, tool_use_result: { backgroundTaskId: "install" } });
        send({ type: "system", subtype: "thinking_tokens", estimated_tokens: 100, estimated_tokens_delta: 100 });
        ready();
        await held;
        send({ type: "result", is_error: true, result: "API Error: test failure", usage: { input_tokens: 10 } });
        child.exitCode = 0;
        return { code: 0, stdout, stderr: "" };
    } });
    await spawned;
    const diskRun = readFileSync(join(runDir, "run.json"), "utf8");
    assert.ok(run.externalExec.captureId, "真实 P6 回调在启动前保存本轮身份");
    assert.equal(run.externalExec.stageStartedAt, start);
    let response;
    const deadline = Date.now() + 5000;
    do { response = await get(); if (response.agentActivity.phase === "thinking") break; await delay(50); } while (Date.now() < deadline);
    const activity = response.agentActivity;
    assert.equal(activity.status, "available"); assert.equal(activity.phase, "thinking");
    assert.equal(activity.captureId, run.externalExec.captureId);
    assert.equal(activity.lastAction.kind, "tool_result"); assert.equal(activity.lastSignalKind, "thinking");
    assert.equal(activity.backgroundTasks[0].status, "running");
    assert.equal(activity.backgroundTasks[0].command, "npm install");
    assert.equal(activity.process.state, "alive"); assert.ok(Date.parse(response.observedAt));
    assert.equal(readFileSync(join(runDir, "run.json"), "utf8"), diskRun, "每次心跳与读取不重写 run.json");
    send({ type: "system", subtype: "task_notification", task_id: "install", tool_use_id: "npm", status: "completed", summary: 'Background command "安装依赖" completed (exit code 0)' });
    complete();
    await execution;
    response = await get();
    assert.equal(response.agentActivity.phase, "failed", "退出码 0 但 API 报错，不能显示成功");
    assert.equal(response.agentActivity.backgroundTasks[0].status, "completed");
    assert.equal(response.agentActivity.backgroundTasks[0].exitCode, 0);
    assert.equal(response.agentActivity.process.state, "unknown", "释放句柄后不能冒称进程存活");
    const messages = readFileSync(join(runDir, "06-implementation/external-exec.messages.jsonl"), "utf8");
    assert.match(messages, /thinking_tokens/); assert.match(messages, /task_notification/);
    const timeline = readFileSync(join(runDir, "06-implementation/external-exec.timeline.log"), "utf8");
    assert.doesNotMatch(timeline, /thinking_tokens/, "心跳不刷屏，完整原始消息仍留存");
    run.stages.P6 = { status: "running", startedAt: new Date(Date.parse(start) + 1).toISOString() };
    saveRun(runDir, run);
    response = await get();
    assert.equal(response.agentActivity.status, "unavailable");
    assert.equal(response.agentActivity.backgroundTasks, undefined, "新阶段不可读取上一轮后台任务");
    const stop = await fetch(base + "/stop", { method: "POST" });
    assert.equal(stop.status, 200);
    const stopped = loadRun(runDir);
    assert.equal(stopped.stages.P6.status, "stopped"); assert.ok(Date.parse(stopped.stages.P6.stoppedAt));
    const stopAgain = await fetch(base + "/stop", { method: "POST" });
    assert.equal(stopAgain.status, 400);
    assert.equal(loadRun(runDir).stages.P6.stoppedAt, stopped.stages.P6.stoppedAt);
    stopped.p6Mode = "dsh"; saveRun(runDir, stopped);
    response = await get();
    assert.equal(response.agentActivity, undefined, "本轮不把 Claude 活动展示到 DSH");
});
